<a href="https://colab.research.google.com/github/Zinniacodes01/Zinnia-s-Code/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split as tts
from sklearn.neighbors import KNeighborsClassifier as KNN

In [ ]:
df=pd.read_csv('Iris.csv')
df['Species']=df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})
x=df.drop('Species',axis=1)
y=df['Species']
trainx,testx,trainy,testy=tts(x,y,test_size=0.2)
model=KNN(n_neighbors=53).fit(trainx,trainy)
y_predict=model.predict(testx)
print(model.score(testx,testy))
print(confusion_matrix(testy,y_predict))

0.9666666666666667
[[ 6  0  0]
 [ 0 11  0]
 [ 0  1 12]]
